- hosts: all
  user: cloud
  sudo: true
  vars_files:
  - vars/master_ip.yml
  tasks:
  - action: selinux state=permissive policy=targeted
  - action: selinux state=disabled policy=targeted
  - include: tasks/puppet-client.yml

  # One-off actions that aren't part of a larger
  # task list.
  - action: shell puppet resource host puppet ip=$master_ip
  - action: copy src=files/user-data-enc dest=/usr/bin/user-data-enc mode=0755
  handlers:
  - include: handlers/services.yml

- hosts: master
  user: cloud
  sudo: true
  tasks:
  - include: tasks/webserver.yml
  handlers:
  - include: handlers/services.yml

- hosts: master
  user: cloud
  sudo: true
  tasks:
  - include: tasks/puppet-master.yml
  - action: copy src=files/master/iptables dest=/etc/sysconfig/iptables
    notify: restart iptables
  handlers:
  - include: handlers/services.yml

